# Generated by Django 4.1 on 2022-12-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_image_product_image_rename_name_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('featured', 'FEATURED'), ('recommended', 'RECOMMENDED'), ('sports', 'SPORTS'), ('groccery', 'GROCERY'), ('clothing', 'CLOTHING'), ('spices', 'SPICES'), ('fruits', 'FRUITS'), ('vegitables', 'VEGITABLES')], default='green', max_length=50),
        ),
    ]
